# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "EasyPatternScanner"
description = "Easy Pattern Scanner"

[target.EasyPatternScannerLib]
type = "library"
headers = ["include/**.h"]
sources = ["src/**.cpp", "src/**.h"]
include-directories = ["include"]

