# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "EasyPatternScanner"
description = "Easy Pattern Scanner"

[target.EasyPatternScanner]
type = "library"
sources = ["src/EasyPatternScanner.cpp"]
